# Section-4
# Covariances

## Name-Komal , Student-id -33275440

In [1]:
import numpy as np

In [2]:
# Given mean values and standard deviations for the four assets
means = np.array([100, 100, 50, 50])
std_devs = np.array([20, 22, 5, 5])

# Correlation matrix for the assets
R = np.array([
    [1.0, 0.9, 0.0, 0.0],
    [0.9, 1.0, -0.9, -0.9],
    [0.0, -0.9, 1.0, 0.5],
    [0.0, -0.9, 0.5, 1.0]
])
print("Correlation matrix: \n",R)

Correlation matrix: 
 [[ 1.   0.9  0.   0. ]
 [ 0.9  1.  -0.9 -0.9]
 [ 0.  -0.9  1.   0.5]
 [ 0.  -0.9  0.5  1. ]]


In [3]:
# Calculating the covariance matrix from the standard deviations and correlation matrix
cov_matrix = np.outer(std_devs, std_devs) * R

# Investment portfolios (weights of investments in the assets)
portfolios = np.array([
    [50, 0, 25, 25],
    [0, 50, 50, 0],
    [0, 50, 25, 25],
    [25, 25, 25, 25]
])
print("Investment portfolios: \n",portfolios)

Investment portfolios: 
 [[50  0 25 25]
 [ 0 50 50  0]
 [ 0 50 25 25]
 [25 25 25 25]]


In [4]:
def portfolio_stats(weights, means, cov_matrix):
    # Calculating the expected value of the portfolio
    expected_value = np.dot(weights, means)
    
    # Calculating the standard deviation of the portfolio
    variance = np.dot(weights, np.dot(cov_matrix, weights))
    std_dev = np.sqrt(variance)
    
    return expected_value, std_dev

In [5]:

# Computing the statistics for each portfolio
results = [portfolio_stats(portfolio, means, cov_matrix) for portfolio in portfolios]

In [6]:
# Displaying the results
for i, result in enumerate(results, 1):
    print(f"Portfolio {i}: Expected Value = {result[0]}, Standard Deviation = {result[1]:.2f}")

Portfolio 1: Expected Value = 7500, Standard Deviation = 1023.17
Portfolio 2: Expected Value = 7500, Standard Deviation = 881.76
Portfolio 3: Expected Value = 7500, Standard Deviation = 872.85
Portfolio 4: Expected Value = 7500, Standard Deviation = 920.26


### For a conservative investor-
We want on minimizing risk while still achieving reasonable returns.The expected value of all the portfolios is same but Portfolio 3 seems to be the most suitable choice for investors .

Portfolio 3 offers a relatively low standard deviation $872.85$ while maintaining the same expected value as the other portfolios. 


## Part II: Mathematical Explanation and Recommendation


Here we are given with four random variables X1,X2,X3,X4


there mean =[100, 100, 50, 50]

standard deviation= [20, 22, 5, 5]

Correlation matrix between the variables is:-

$\left(
\begin{array}{cccc}
1.0 & 0.9 & 0.0 & 0.0 \\
0.9 & 1.0 & -0.9 & -0.9 \\
0.0 & -0.9 & 1.0 & 0.5 \\
0.0 & -0.9 & 0.5 & 1.0 \\
\end{array}
\right)
 $



### Expected Value
The expected value of a portfolio represents the average outcome of an investment over a long period under current conditions. It is calculated by taking the dot product of the portfolio weights  and the mean values of the assets.

Mathematically, the expected value 
E[P] of a portfolio P that consists of a combination of assets can be calculated using the formula:


$E[P] = \sum_{i=1}^{n} w_i \mu_i $


where $w_i$ represents the weight of the i the asset in the portfolio,

and $\mu_i$ is the mean (expected return) of the asset. 

This  computes a weighted average of the expected returns of the individual assets, where the weights reflect the proportion of the total portfolio value represented by each asset.

### Covariance Matrix
The covariance matrix measures how changes in one asset's returns are expected to correlate with changes in another's. For assets 
i and j, the covariance σ_i is calculated as:

$\sigma_{ij} = \rho_{ij} \sigma_i \sigma_j
$

 where $ \rho_{ij}$  is the correlation coefficient between the returns of assets i and j.

&

$ \sigma_i and \sigma_j $are the standard deviations of assets 
i and j respectively. 

The correlation matrix R consists of all pairwise correlation coefficients $ \rho_{ij}$ , and when multiplied element-wise by the outer product of the standard deviations vector with itself, it produces the covariance matrix. 

### The variance of a portfolio 
$\sigma_P^2$ provides a measure of the spread of the returns around the expected value, representing the risk associated with the portfolio. It is calculated using:

$\sigma_P^2 = \mathbf{w}^T \Sigma \mathbf{w}$
#### variance = np.dot(weights, np.dot(cov_matrix, weights))

where w is the vector of portfolio weights and 

$\Sigma $ is the covariance matrix. The standard deviation, which is the square root of the variance, directly measures the expected volatility of the portfolio's returns. 




### Standard deviation -It is crucial for investors as it helps in understanding the amount of risk involved in the portfolio relative to the returns.
It is simply the square root of the variance. It is measure of the total risk  of the portfolio's returns, indicating the typical deviation from the expected value.
$\sigma_P = \sqrt{\sigma_P^2}
$

### Portfolio 3: The Conservative Choice
Given that all portfolios have the same expected value, a conservative investor would ideally choose the portfolio with the lowest standard deviation, as it implies lower risk or less fluctuation in returns. Portfolio 3, having the lowest standard deviation among the given portfolios, thus represents the optimal choice for minimizing risk while maintaining expected returns.

